### ISSUE TITLE
关于您的SparseTIR论文解读博客

### ISSUE THREAD

**Issue by yzh119** [topdeoo/topdeoo.github.io#1]
感谢您对sparsetir的解读，关于这个论断：
https://github.com/topdeoo/topdeoo.github.io/blob/5db5dc7255f0abee57712abcdbb91a1f1c093b7f/src/posts/ICT%20AI%20Compilers/SparseTIR.md?plain=1#L1054

我们的[artifact](https://github.com/uwsampl/sparsetir-artifact)包含了复现所有实验（包括baseline）的源码。

**Comment by topdeoo** [comment]
> 感谢您对sparsetir的解读，关于这个论断：
> 
> https://github.com/topdeoo/topdeoo.github.io/blob/5db5dc7255f0abee57712abcdbb91a1f1c093b7f/src/posts/ICT%20AI%20Compilers/SparseTIR.md?plain=1#L1054
> 
> 我们的[artifact](https://github.com/uwsampl/sparsetir-artifact)包含了复现所有实验（包括baseline）的源码。

您好，感谢您的阅读与指正，我为我没有详细阅读论文附录部分而做出的错误论断道歉

此内容已在文章中补充修改
